services:
    ok99.privatezone.classification.admin.tag:
        class: Ok99\PrivateZoneCore\ClassificationBundle\Admin\TagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Classification, label: tags }
        arguments: [null, Ok99\PrivateZoneCore\ClassificationBundle\Entity\Tag, null]

    sonata.classification.admin.category:
        class: Ok99\PrivateZoneCore\ClassificationBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sonata_classification, label: label_categories, label_translator_strategy: sonata.admin.label.strategy.underscore }
        arguments: [null, Ok99\PrivateZoneCore\ClassificationBundle\Entity\Category, %sonata.classification.admin.category.controller%, @sonata.classification.manager.context, @ok99.privatezone.site.pool]
