<?php

namespace Ok99\PrivateZoneCore\ClassificationBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Ok99\PrivateZoneCore\ClassificationBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    protected function createDocumentsQuery()
    {
        return $this->createQueryBuilder('c')
            ->where('c.context = :context')
            ->andWhere('c.enabled = :true')
            ->andWhere('c.parent IS NOT NULL')
            ->orderBy('c.position')
            ->setParameter('context', 'documents')
            ->setParameter('true', true);
    }

    /**
     * @return Category
     */
    public function getDocumentsCategory()
    {
        try {
            return $this->createDocumentsQuery()
                ->setMaxResults(1)
                ->getQuery()
                ->getSingleResult();
        } catch (NoResultException $e) {
            return null;
        }
    }

    /**
     * @return Category[]
     */
    public function getDocumentsCategories()
    {
        try {
            return $this->createDocumentsQuery()
                ->getQuery()
                ->getResult();
        } catch (NoResultException $e) {
            return [];
        }
    }
}
